### ISSUE TITLE
Refactor `projects.json` file to support upcoming features

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-project-manager#47]
The `projects.json` file structure must be refactored to support upcoming features like:
- [x] #43 - Load project list from directory
- [x] #46 - Support multiple folders in the same project
- [x] #50 - Contextual Structure - Grouping

**Comment by alefragnani** [comment]
#46 and #50 still depends on VS Code core updates, but _it is already prepared _.
