### ISSUE TITLE
[FEATURE] - Improve Favorites Side Bar

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-project-manager#526]
Add new customization options

- [ ] Hide/Show Disabled (#368)
- [ ] Hide/Show Counters
- [ ] Hide/Show Projects without Tags
- [ ] Kinds/Types (#481)
  - [ ] Folders
  - [ ] Workspaces (multi-root)
  - [ ] Remotes
    - [ ] Container
    - [ ] SSH
    - [ ] WSL
    - [ ] Codespaces
    - [ ] Remote Repository
- [x] View & Sort
  - [x] View as List / Tags (#534)
  - [x] Sort by _`projectManager.sortList` setting_ (#484)

**Comment by pandc** [comment]
Hi Alessandro,

I would appreciate an option to start with all the tags collapsed or a command to do that.
IMO this would allow a faster access to other projects.

Thanks,
Angelo

**Comment by alefragnani** [comment]
Hi @pandc ,

The collapsed feature for tags is being tracked in #556 ,  #566 and #778. 

Stay tuned for upcoming releases

**Comment by alefragnani** [comment]
I'm closing this feature request because it is more like a centralization/management issue, and right now thee is only one still open.
